// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52DRZkbTBBlJL8Ws3Lbw9X5nCkQTcRHg',
    appId: '1:347905549781:web:a932259fb7b3577e5b095c',
    messagingSenderId: '347905549781',
    projectId: 'recruter-7c78a',
    authDomain: 'recruter-7c78a.firebaseapp.com',
    storageBucket: 'recruter-7c78a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfdcDkI29LjYCem-wNBiTxvAs3Ft9r3I',
    appId: '1:347905549781:android:141fbd9f781f798b5b095c',
    messagingSenderId: '347905549781',
    projectId: 'recruter-7c78a',
    storageBucket: 'recruter-7c78a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC52DRZkbTBBlJL8Ws3Lbw9X5nCkQTcRHg',
    appId: '1:347905549781:web:bdf8f99209a3bef05b095c',
    messagingSenderId: '347905549781',
    projectId: 'recruter-7c78a',
    authDomain: 'recruter-7c78a.firebaseapp.com',
    storageBucket: 'recruter-7c78a.appspot.com',
  );

}